node_transform_broadcast:
  ros__parameters:
    # 激光雷达到车身坐标系的转换
    lidar_to_vehicle:
      translation:
        x: 0.5  # 前后方向偏移
        y: 0.0  # 左右方向偏移
        z: 1.8  # 上下方向偏移
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    # 相机到激光雷达的转换
    camera_to_lidar:
      translation:
        x: 0.1
        y: 0.0
        z: 0.2
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    # 组合惯导到车身坐标系的转换
    imu_to_vehicle:
      translation:
        x: 0.0
        y: 0.0
        z: 0.0
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0