node_transform_coordinate:
  ros__parameters:
    #corner radar parameters
    #left_top
    left_top_corner_radar_theta: 30.0
    left_top_corner_radar_x: 20.0
    left_top_corner_radar_y: 20.0 
    left_top_corner_radar_z: 10.0
    #right_top
    right_top_corner_radar_theta: 30.0
    right_top_corner_radar_x: -20.0
    right_top_corner_radar_y: 20.0
    right_top_corner_radar_z: 10.0
    #left_back
    left_back_corner_radar_theta: 150.0
    left_back_corner_radar_x: 20.0
    left_back_corner_radar_y: -20.0
    left_back_corner_radar_z: 10.0
    #right_back
    right_back_corner_radartheta: 150.0
    right_back_corner_radar_x: -20.0
    right_back_corner_radar_y: -20.0
    right_back_corner_radar_z: 10.0
    #top_front
    top_front_corner_radar_theta: 0
    top_front_corner_radar_x: 10.0
    top_front_corner_radar_y: 10.0
    top_front_corner_radar_z: 10.0
    #lidar parameters
    #yaw 航向角，绕z轴逆时针旋转角度为正，单位为度  物体在水平面上的方向变化，航向偏移反映为车辆行进方向变化
    lidar_yaw: 30.0
    #pitch 俯仰角，绕y轴逆时针旋转角度为正，单位为度  俯仰角表示车辆的前后倾斜
    lidar_pitch: 30.0
    #roll 横滚角，绕x轴逆时针旋转角度为正，单位为度  横滚角表示车辆的左右倾斜
    lidar_roll: 30.0
    lidar_x: 10.0
    lidar_y: 10.0
    lidar_z: 10.0
    #camera parameters
    #camera Intrinsic Parameters
    camera_fx: 525.0
    camera_fy: 525.0
    camera_cx: 319.5
    camera_cy: 239.5
    #camera extrinsic Parameters
    camera_roll: 30.0
    camera_pitch: 50.0
    camera_yaw: 70.0
    camera_x: 0.5
    camera_y: -1.0
    camera_z: 2.0

    
