node_can:
  ros__parameters:
    max_steer_angle: 470.0
    max_steer_angle_spd: 500.0
    min_steer_angle_spd: 100.0
    max_acc: 5.0
    min_acc: -5.0
    max_brake_pressure: 7.0
    driving_mode: 2
    can_interface: vcan0