perception_node:
  ros__parameters:
    max_height: 3.0
    min_height: 0.0
    vehicle_height: 1.6
    vehicle_length: 4.9
    vehicle_width: 1.8
    radar_height: 0.3
    roi_width: 1.0
    cluster_tolerance: 0.4 # 最小可容忍点云点距离，单位米
    min_cluster_size: 20
    max_cluster_size: 30000
    leaf_size: 0.1
    plane_point_percent : 0.5 # 平面内点云点比例
    lidar_base_x: 0.0
    lidar_base_y: 0.0
    lidar_base_z: 0.0
    lidar_base_yaw: 180.0
    lidar_base_pitch: 0.0
    lidar_base_roll: 0.0
    radar_base_x: 0.0
    radar_base_y: 0.0
    radar_base_z: 0.0
    radar_base_yaw: 0.0
    radar_base_pitch: 0.0
    radar_base_roll: 0.0
    # debug_para
    enable_visualization: false
    enable_use_roi: false
    enable_calculate_process_time: false
    enable_downsample: true
    segment_ground_type: 1 # 1:algorithm, 2:based on height
