map_node:
  ros__parameters:
    # 地图文件目录 (相对于项目根目录)
    map_files_dir: "~/auto_clean_bot/map_files"
    
    # 边界类型（用于组装文件名）
    boundary_type: 7
    
    # 边界名称
    left_boundary_name: "left_boundary"
    right_boundary_name: "right_boundary"
    
    # 边界长度
    boundary_length: 19.0
    
    # 发布频率
    publish_frequency: 10.0

    # 简化的最近点搜索参数
    direction_stability_weight: 2.0  # 连续性权重（避免大幅跳跃）
    max_index_jump: 100.0            # 最大索引跳跃限制（点数）

   
    bkpoint_end_path_type : 13  # 断点测试的结束路径类型
    cyclic_test_path_type : 29 # 循环测试路径类型
    cyclic_test_end_dis : 5.0  # 循环测试模式下的终点距离